baseurl = "/"
DefaultContentLanguage = "de"
title = "AUTOHAUS PERRONE"

enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    locale = "de_DE"
    weight = 1

[params]
